FROM quay.io/keycloak/keycloak:latest

ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=1234
ENV KC_HOSTNAME=osamhack2022-web-mili-meet-broker-g55g59rv9qjhwwq5-8080.githubpreview.dev
ENV KC_HOSTNAME_ADMIN_URL=https://osamhack2022-web-mili-meet-broker-g55g59rv9qjhwwq5-8080.githubpreview.dev
ENV KC_HOSTNAME_STRICT_HTTPS=true
ENV KC_HOSTNAME_PORT=443

CMD [ "start-dev" ]
